---
apiVersion: v1
kind: Namespace
metadata:
  name: project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydeploy
  name: mydeploy
  namespace: project
spec:
  replicas: 4
  strategy:
          type: RollingUpdate
          rollingUpdate:
                  maxSurge: 1
                  maxUnavailable: 1
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
      - image: nginx
        name: nginx
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
  namespace: project
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: mydeploy
  type: NodePort
